apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: biorobot-vault-bridge
spec:
  refreshInterval: "15s" # Automatically rotates if you change it in AWS!
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: biorobot-k8s-secret # This is the name K8s will use locally
  data:
  - secretKey: private_key
    remoteRef:
      key: biorobot/fleet-alpha/private-key # Matches the name in AWS